# Generated by Django 4.0.3 on 2022-07-14 02:00

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=300)),
                ('nota', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)])),
                ('data_criacao', models.DateTimeField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Filtro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=45, null=True)),
                ('area', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('C', 'Ciencias'), ('B', 'Biologia'), ('S', 'Sociedade'), ('E', 'Engenharias'), ('L', 'Linguística'), ('P', 'Política'), ('P', 'História')], default=['CET', 'CB', 'CSA', 'E', 'LLA', 'CH'], max_length=40, null=True)),
                ('tema', models.CharField(blank=True, default='All', max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Redacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=45)),
                ('area', multiselectfield.db.fields.MultiSelectField(choices=[('C', 'Ciencias'), ('B', 'Biologia'), ('S', 'Sociedade'), ('E', 'Engenharias'), ('L', 'Linguística'), ('P', 'Política'), ('P', 'História')], max_length=20)),
                ('tema', models.CharField(max_length=45)),
                ('data_criacao', models.DateTimeField(default=datetime.date.today)),
                ('conteudo', models.TextField(max_length=15000)),
                ('descricao', models.TextField(blank=True, default=None, max_length=300, null=True)),
                ('compartilhamentos', models.SmallIntegerField(default=0)),
                ('avaliacoes', models.ManyToManyField(related_name='redacoesAvaliadas', through='RedifApp.Avaliacao', to='accounts.usuario')),
                ('fk_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Redacao', to='accounts.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='redacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_avaliacao', to='RedifApp.redacao'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_avaliacao', to='accounts.usuario'),
        ),
    ]
